[doctor]
checks = [
  { check = "homebrew" },
]

[audit]
checks = [
  { name = "audit", shell = "shellcheck -e SC1091,SC2181 share/*" },
]

[update]
steps = [
  { step = "git", command = "pull" },
  { doctor = {} },
]

[test]
checks = []

[shipit]
steps = [
  { audit = {} },
  { update = {} },
  { test = {} },
  # { name = "Release", shell = "bin/dev/release", verbose = true },
  { step = "git", command = "push" },
  { step = "github", command = "link-to-actions", verbose = true },
]
